

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for jellyfin
LUCI_DEPENDS:=+luci-app-dockerman
LUCI_PKGARCH:=all
PKG_VERSION:=1.0.0
PKG_RELEASE:=20210906

include $(TOPDIR)/feeds/luci/luci.mk

